name: Run Test Suite
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Run testsuite
        using: 'docker'
        image: 'Dockerfile'
        run: python3 -m unittest discover -v -s test/ -p 'test_*.py'
